apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: tailspin-web
  name: tailspin-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailspin-web
  template:
    metadata:
      labels:
        app: tailspin-web
    spec:
      containers:
      - image: darkaru/tailspin:20
        imagePullPolicy: Always
        name: tailspin-web
        ports:
        - containerPort: 80
          protocol: TCP